version: "3.5"

services:
  app:
    build:
      context: .
      cache_from: [ghcr.io/friends-of-forkcms/fork-cms-module-commerce:latest]
      args:
        THEME_NAME: CommerceDemo
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=forkcms
      - DB_USER=forkcms
      - DB_PASSWORD=forkcms
      - FORK_ENV=prod
      - FORK_DEBUG=1
      - SITE_DOMAIN=localhost
      - SMTP_USERNAME=dummy_smtp_username___1234567890
      - SMTP_PASSWORD=dummy_smtp_password___1234567890
    volumes:
      - ./deploy:/var/www/html/deploy
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  db:
    image: "mariadb:10"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=forkcms
      - MYSQL_ROOT_PASSWORD=kingtriton
      - MYSQL_USER=forkcms
      - MYSQL_PASSWORD=forkcms
    volumes:
      - ./deploy/mysql:/docker-entrypoint-initdb.d
