apiVersion: v1
kind: Service
metadata:
  name: fork-cms-module-commerce-demo
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: fork-cms-module-commerce-demo
  type: ClusterIP
  ports:
    - port: 80
