<?php

namespace Backend\Modules\CommerceCashOnDelivery\Domain\CashOnDelivery\Command;

use Backend\Modules\CommerceCashOnDelivery\Domain\CashOnDelivery\CashOnDeliveryPaymentMethodDataTransferObject;

class UpdateCashOnDeliveryPaymentMethod extends CashOnDeliveryPaymentMethodDataTransferObject
{
}
