apiVersion: v1
kind: Service
metadata:
  name: module-commerce
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: module-commerce
  type: ClusterIP
  ports:
    - name: p-80-80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: p-443-443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
