# Must be placed in a seperate subfolder to avoid conflicts with Gedmo
# See: https://github.com/doctrine-extensions/DoctrineExtensions/blob/HEAD//doc/symfony4.md#troubleshooting
Money\Currency:
  type: embeddable
  fields:
    code:
      type: string
      length: 3
      column: Code
