services:
    commerce.handler.update_shipment_method_pickup:
        class: Backend\Modules\CommercePickup\Domain\Pickup\Command\UpdatePickupShipmentMethodHandler
        arguments:
            - "@commerce.repository.shipment_method"
            - "@fork.settings"
        tags:
            - { name: command_handler, handles: Backend\Modules\CommercePickup\Domain\Pickup\Command\UpdatePickupShipmentMethod }
