# Check documentation at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Use docker-based setup for running tests since the docker-setup already contains all bootstrapping scripts
# Inspired by api-platform's CI.yml
name: CI

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: PHPUnit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull images
        run: docker-compose pull --ignore-pull-failures || true

      - name: Start services
        run: docker-compose up --build -d

      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy)
                docker-compose ps
                docker-compose logs
                exit 1
              ;;
            esac
          done
          exit 1

      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost

      - name: Check HTTPS reachability
        run: curl  -vk -o /dev/null https://localhost

      - name: PHPUnit
        run: docker-compose exec -T php bin/simple-phpunit --coverage-clover=coverage.clover --filter '\\Modules\\Commerce\\'

      - name: Display error logs on failure
        if: failure()
        run: |
          docker-compose ps
          docker-compose logs
