on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "30 6 * * *"  # Runs at 06:30 UTC every day
    - cron: "30 18 * * *" # Runs at 18:30 UTC every day

concurrency:
  group: 'deploy-demo-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

name: Deploy Demo
jobs:
  deploy-demo-app:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository_owner == 'friends-of-forkcms'
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      # Namespace must be the GitHub ID or suffixed with it.
      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: jessedobbelaere

      - name: Deploy Pipeline
        uses: okteto/pipeline@master
        with:
          name: "fork-cms-module-commerce-demo"
          timeout: 15m
          variables: "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }},SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"

      - name: Verify up and running
        uses: nev7n/wait_for_response@v1
        with:
          url: "https://preview-module-commerce-jessedobbelaere.cloud.okteto.net/en"
          responseCode: 200
          timeout: 600000 # 10min
          interval: 5000 # 5s
