on:
  pull_request:
    branches:
      - master

env:
  DEPLOY_NAME: fork-cms-module-commerce-demo-pr-${{ github.event.number }}

name: Deploy Preview PR
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: jessedobbelaere

      - name: Deploy Pipeline
        uses: okteto/pipeline@master
        with:
          name: ${{ env.DEPLOY_NAME }}
          timeout: 10m

      - name: Verify up and running
        uses: nev7n/wait_for_response@v1
        with:
          url: "https://${{ env.DEPLOY_NAME }}-jessedobbelaere.cloud.okteto.net/en"
          responseCode: 200
          timeout: 600000 # 10min
          interval: 5000 # 5s

      - name: Comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "🚀 Preview environment available at https://${{ env.DEPLOY_NAME }}-jessedobbelaere.cloud.okteto.net for the next 24 hours."
