on:
  pull_request:
    branches:
      - master

env:
  # Name of the preview environment in okteto.com
  # Will be prefixed with the actual deploy name. Must be suffixed with the github ID!
  # e.g. end result: https://preview-module-commerce-pr-26-jessedobbelaere.cloud.okteto.net
  DEPLOY_NAME: pr-${{ github.event.number }}-jessedobbelaere

# Kill the previous job in progress, when multiple job start (e.g. committing multiple times)
concurrency:
  group: 'preview-pr-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

# See: https://okteto.com/docs/tutorials/preview-environments/#step-2-create-the-github-workflow
name: Deploy Preview PR
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        with:
          name: ${{ env.DEPLOY_NAME }}
          timeout: 15m

      - name: Verify up and running
        uses: nev7n/wait_for_response@v1
        with:
          url: "https://preview-module-commerce-${{ env.DEPLOY_NAME }}.cloud.okteto.net/en"
          responseCode: 200
          timeout: 600000 # 10min
          interval: 5000 # 5s
