on:
  pull_request:
    branches:
      - master

env:
  DEPLOY_NAME: pr-${{ github.event.number }}-jessedobbelaere

# Kill the previous job in progress, when multiple job start (e.g. committing multiple times)
concurrency:
  group: preview-pr-${{ github.head_ref }}
  cancel-in-progress: true

# See: https://okteto.com/docs/tutorials/preview-environments/#step-2-create-the-github-workflow
name: Deploy Preview PR
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.DEPLOY_NAME }}
          timeout: 20m
